Programme: main.o treasurequest.o 
	gcc -o Programme main.o treasurequest.o -Wextra -lm

main.o: main.c  
	gcc -c main.c -Wextra -lm

treasurequest.o: treasurequest.c 
	gcc -c treasurequest.c -Wextra -lm

